modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="MIT" #mandatory
issueTrackerURL="https://github.com/SihenZhang/CrockPot/issues" #optional
[[mods]] #mandatory
modId="crockpot" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Crock Pot" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/crock-pot" #optional
logoFile="banner.png" #optional
credits="charged_coconut,MisterPlus,MalayP" #optional
authors="Si_hen,idyllicbean,SeraphJack,UnknownWhite" #optional
description='''
Bring Crock Pot from Don't Starve to Minecraft.
'''
[[dependencies.crockpot]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.crockpot]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
